# Generated by Django 4.0.3 on 2022-05-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questiontext', models.CharField(max_length=200, null=True)),
                ('first', models.CharField(max_length=200, null=True)),
                ('second', models.CharField(max_length=200, null=True)),
                ('third', models.CharField(max_length=200, null=True)),
                ('fourth', models.CharField(max_length=200, null=True)),
                ('ans', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
